server:
  port: 8082

spring:
  application:
    name: chatbot-ai-demo

  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  seeder:
    enabled: true
  ai:
    openai:
      api-key:
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash