spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer_security_db_2?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    format-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/master}
          # audiences: backend-spring   # (optional, to check aud for BE client to connect FE client)
          # jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:8080/realms/master/protocol/openid-connect/certs}
    
server:
  port: 8081
