spring:
  data:
    mongodb:
      url: mongodb://localhost:27017/cc/customer_management_v2

server:
  port: 8082

logging:
  level:
    org:
      springframework:
        data:
          mongodb=DEBUG: