spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer_management?useSSL=false
    username: root
    password: root


jpa:
  hibernate:
    ddl-auto: none
  show-sql: true
  format-sql: true
  database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 8083