spring:
  datasource:
    url: jdbc:h2:mem:chatbotdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

openai:
  api:
    key:
  model: gpt-3.5-turbo

server:
  port: 8082
