spring:
    application:
        name: redis-optimized

    datasource:
        url: jdbc:postgresql://localhost:5432/redisTest?TimeZone=Asia/Ho_Chi_Minh
        username: postgres
        password: postgres123
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate:
                format_sql: true
                jdbc:
                    time_zone: Asia/Ho_Chi_Minh

    data:
        redis:
            host: localhost
            port: 6379
            password:
            database: 0
            timeout: 2s
            lettuce:
                pool:
                    max-total: 100
                    max-idle: 50
                    min-idle: 10
                    max-wait: 1s
            cluster:
                nodes:

        cache:
            type: redis
            redis:
                default-ttl: 10m
                cache-ttls:
                    customers: 30m

    flyway:
        enabled: true
        baseline-on-migrate: true
        baseline-version: 1.0
        default-schema: public
        schemas: public
        locations: classpath:db/migration
        table: flyway_schema_history

server:
    port: 8080

management:
    endpoints:
        web:
            exposure:
                include: health,metrics,caches

logging:
    level:
        org.hibernate.SQL: debug


debug: true